/**
 * Instrument Universe Definitions
 *
 * Edit this file to change the default watchlist universe.
 * Add custom watchlists by appending to WATCHLISTS below.
 * All ticker lists are loaded server-side — never exposed in client bundles.
 */

export interface UniverseInstrument {
  symbol: string;
  name: string;
  sector: string;
  industry?: string;
  type: "stock" | "etf" | "index";
  marketCapBucket?: "mega" | "large" | "mid" | "small"; // rough sizing for treemap weight
  weight?: number; // optional manual weight override
  // Approximate shares outstanding (in whole shares). Used to compute
  // implied market cap = endClose × sharesOutstanding. Update periodically
  // as shares change via buybacks or issuances. Source: SEC filings / Yahoo Finance.
  sharesOutstanding?: number;
}

// ─── Magnificent 7 ────────────────────────────────────────────────────────────
// sharesOutstanding: approximate diluted shares as of early 2026 (whole shares).
// Source: latest SEC 10-Q/10-K filings. Update as needed.
export const MAG7: UniverseInstrument[] = [
  { symbol: "AAPL", name: "Apple",     sector: "Technology",             industry: "Consumer Electronics", type: "stock", marketCapBucket: "mega", sharesOutstanding: 15_022_000_000 },
  { symbol: "MSFT", name: "Microsoft", sector: "Technology",             industry: "Software",             type: "stock", marketCapBucket: "mega", sharesOutstanding:  7_433_000_000 },
  { symbol: "NVDA", name: "NVIDIA",    sector: "Technology",             industry: "Semiconductors",       type: "stock", marketCapBucket: "mega", sharesOutstanding: 24_370_000_000 },
  { symbol: "GOOGL", name: "Alphabet", sector: "Communication Services", industry: "Internet",             type: "stock", marketCapBucket: "mega", sharesOutstanding: 12_000_000_000 },
  { symbol: "AMZN", name: "Amazon",    sector: "Consumer Discretionary", industry: "E-Commerce",           type: "stock", marketCapBucket: "mega", sharesOutstanding: 10_550_000_000 },
  { symbol: "META", name: "Meta",      sector: "Communication Services", industry: "Social Media",         type: "stock", marketCapBucket: "mega", sharesOutstanding:  2_545_000_000 },
  { symbol: "TSLA", name: "Tesla",     sector: "Consumer Discretionary", industry: "Electric Vehicles",    type: "stock", marketCapBucket: "mega", sharesOutstanding:  3_210_000_000 },
];

// ─── S&P 500 — Full index (~490 constituents) ─────────────────────────────────
export const SP500: UniverseInstrument[] = [
  // ── Information Technology (~64) ─────────────────────────────────────────
  { symbol: "AAPL",  name: "Apple",                      sector: "Technology", industry: "Consumer Electronics",      type: "stock", marketCapBucket: "mega"  },
  { symbol: "MSFT",  name: "Microsoft",                  sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "mega"  },
  { symbol: "NVDA",  name: "NVIDIA",                     sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "mega"  },
  { symbol: "AVGO",  name: "Broadcom",                   sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "mega"  },
  { symbol: "ORCL",  name: "Oracle",                     sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "mega"  },
  { symbol: "CRM",   name: "Salesforce",                 sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "AMD",   name: "AMD",                        sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "large" },
  { symbol: "INTC",  name: "Intel",                      sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "large" },
  { symbol: "QCOM",  name: "Qualcomm",                   sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "large" },
  { symbol: "TXN",   name: "Texas Instruments",          sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "large" },
  { symbol: "AMAT",  name: "Applied Materials",          sector: "Technology", industry: "Semiconductor Equipment",   type: "stock", marketCapBucket: "large" },
  { symbol: "ADI",   name: "Analog Devices",             sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "large" },
  { symbol: "MU",    name: "Micron Technology",          sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "large" },
  { symbol: "LRCX",  name: "Lam Research",               sector: "Technology", industry: "Semiconductor Equipment",   type: "stock", marketCapBucket: "large" },
  { symbol: "KLAC",  name: "KLA Corp",                   sector: "Technology", industry: "Semiconductor Equipment",   type: "stock", marketCapBucket: "large" },
  { symbol: "NOW",   name: "ServiceNow",                 sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "ADSK",  name: "Autodesk",                   sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "SNPS",  name: "Synopsys",                   sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "CDNS",  name: "Cadence Design",             sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "FTNT",  name: "Fortinet",                   sector: "Technology", industry: "Cybersecurity",             type: "stock", marketCapBucket: "large" },
  { symbol: "PANW",  name: "Palo Alto Networks",         sector: "Technology", industry: "Cybersecurity",             type: "stock", marketCapBucket: "large" },
  { symbol: "CRWD",  name: "CrowdStrike",                sector: "Technology", industry: "Cybersecurity",             type: "stock", marketCapBucket: "large" },
  { symbol: "INTU",  name: "Intuit",                     sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "IBM",   name: "IBM",                        sector: "Technology", industry: "IT Services",               type: "stock", marketCapBucket: "large" },
  { symbol: "HPQ",   name: "HP Inc",                     sector: "Technology", industry: "Computer Hardware",         type: "stock", marketCapBucket: "large" },
  { symbol: "HPE",   name: "Hewlett Packard Enterprise", sector: "Technology", industry: "IT Services",               type: "stock", marketCapBucket: "large" },
  { symbol: "CSCO",  name: "Cisco",                      sector: "Technology", industry: "Networking",                type: "stock", marketCapBucket: "large" },
  { symbol: "ACN",   name: "Accenture",                  sector: "Technology", industry: "IT Services",               type: "stock", marketCapBucket: "large" },
  { symbol: "IT",    name: "Gartner",                    sector: "Technology", industry: "IT Services",               type: "stock", marketCapBucket: "large" },
  { symbol: "CTSH",  name: "Cognizant",                  sector: "Technology", industry: "IT Services",               type: "stock", marketCapBucket: "large" },
  { symbol: "MSI",   name: "Motorola Solutions",         sector: "Technology", industry: "Communications Equipment",  type: "stock", marketCapBucket: "large" },
  { symbol: "NTAP",  name: "NetApp",                     sector: "Technology", industry: "Data Storage",              type: "stock", marketCapBucket: "large" },
  { symbol: "NXPI",  name: "NXP Semiconductors",         sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "large" },
  { symbol: "ON",    name: "ON Semiconductor",           sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "large" },
  { symbol: "PLTR",  name: "Palantir",                   sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "PTC",   name: "PTC Inc",                    sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "TEL",   name: "TE Connectivity",            sector: "Technology", industry: "Electronic Components",     type: "stock", marketCapBucket: "large" },
  { symbol: "TER",   name: "Teradyne",                   sector: "Technology", industry: "Semiconductor Equipment",   type: "stock", marketCapBucket: "large" },
  { symbol: "TYL",   name: "Tyler Technologies",         sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "VRSN",  name: "VeriSign",                   sector: "Technology", industry: "Internet Services",         type: "stock", marketCapBucket: "large" },
  { symbol: "WDC",   name: "Western Digital",            sector: "Technology", industry: "Data Storage",              type: "stock", marketCapBucket: "large" },
  { symbol: "ZBRA",  name: "Zebra Technologies",         sector: "Technology", industry: "Electronic Equipment",      type: "stock", marketCapBucket: "large" },
  { symbol: "GLW",   name: "Corning",                    sector: "Technology", industry: "Electronic Components",     type: "stock", marketCapBucket: "large" },
  { symbol: "APH",   name: "Amphenol",                   sector: "Technology", industry: "Electronic Components",     type: "stock", marketCapBucket: "large" },
  { symbol: "CDW",   name: "CDW Corp",                   sector: "Technology", industry: "IT Distribution",           type: "stock", marketCapBucket: "large" },
  { symbol: "SWKS",  name: "Skyworks Solutions",         sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "large" },
  { symbol: "STX",   name: "Seagate Technology",         sector: "Technology", industry: "Data Storage",              type: "stock", marketCapBucket: "large" },
  { symbol: "FFIV",  name: "F5 Inc",                     sector: "Technology", industry: "Networking",                type: "stock", marketCapBucket: "large" },
  { symbol: "ANSS",  name: "Ansys",                      sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "AKAM",  name: "Akamai",                     sector: "Technology", industry: "Internet Services",         type: "stock", marketCapBucket: "large" },
  { symbol: "JKHY",  name: "Jack Henry",                 sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "BR",    name: "Broadridge Financial",       sector: "Technology", industry: "IT Services",               type: "stock", marketCapBucket: "large" },
  { symbol: "GEN",   name: "Gen Digital",                sector: "Technology", industry: "Cybersecurity",             type: "stock", marketCapBucket: "large" },
  { symbol: "GDDY",  name: "GoDaddy",                    sector: "Technology", industry: "Internet Services",         type: "stock", marketCapBucket: "large" },
  { symbol: "GRMN",  name: "Garmin",                     sector: "Technology", industry: "Electronic Equipment",      type: "stock", marketCapBucket: "large" },
  { symbol: "KEYS",  name: "Keysight Technologies",      sector: "Technology", industry: "Electronic Test Equipment", type: "stock", marketCapBucket: "large" },
  { symbol: "MPWR",  name: "Monolithic Power Systems",   sector: "Technology", industry: "Semiconductors",            type: "stock", marketCapBucket: "large" },
  { symbol: "EPAM",  name: "EPAM Systems",               sector: "Technology", industry: "IT Services",               type: "stock", marketCapBucket: "large" },
  { symbol: "FSLR",  name: "First Solar",                sector: "Technology", industry: "Solar Energy",              type: "stock", marketCapBucket: "large" },
  { symbol: "SMCI",  name: "Super Micro Computer",       sector: "Technology", industry: "Computer Hardware",         type: "stock", marketCapBucket: "large" },
  { symbol: "DELL",  name: "Dell Technologies",          sector: "Technology", industry: "Computer Hardware",         type: "stock", marketCapBucket: "large" },
  { symbol: "ROP",   name: "Roper Technologies",         sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "TRMB",  name: "Trimble",                    sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "ENPH",  name: "Enphase Energy",             sector: "Technology", industry: "Solar Energy",              type: "stock", marketCapBucket: "large" },
  { symbol: "PAYC",  name: "Paycom Software",            sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "ADBE",  name: "Adobe",                      sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "WDAY",  name: "Workday",                    sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "VEEV",  name: "Veeva Systems",              sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "TEAM",  name: "Atlassian",                  sector: "Technology", industry: "Software",                  type: "stock", marketCapBucket: "large" },
  { symbol: "SNOW",  name: "Snowflake",                  sector: "Technology", industry: "Cloud Data Platform",       type: "stock", marketCapBucket: "large" },

  // ── Communication Services (~23) ─────────────────────────────────────────
  { symbol: "GOOGL", name: "Alphabet (A)",               sector: "Communication Services", industry: "Internet",          type: "stock", marketCapBucket: "mega"  },
  { symbol: "GOOG",  name: "Alphabet (C)",               sector: "Communication Services", industry: "Internet",          type: "stock", marketCapBucket: "mega"  },
  { symbol: "META",  name: "Meta Platforms",             sector: "Communication Services", industry: "Social Media",      type: "stock", marketCapBucket: "mega"  },
  { symbol: "NFLX",  name: "Netflix",                    sector: "Communication Services", industry: "Streaming",         type: "stock", marketCapBucket: "large" },
  { symbol: "DIS",   name: "Walt Disney",                sector: "Communication Services", industry: "Entertainment",     type: "stock", marketCapBucket: "large" },
  { symbol: "CMCSA", name: "Comcast",                    sector: "Communication Services", industry: "Cable & Telecom",   type: "stock", marketCapBucket: "large" },
  { symbol: "T",     name: "AT&T",                       sector: "Communication Services", industry: "Telecom",           type: "stock", marketCapBucket: "large" },
  { symbol: "VZ",    name: "Verizon",                    sector: "Communication Services", industry: "Telecom",           type: "stock", marketCapBucket: "large" },
  { symbol: "CHTR",  name: "Charter Communications",     sector: "Communication Services", industry: "Cable & Telecom",   type: "stock", marketCapBucket: "large" },
  { symbol: "TMUS",  name: "T-Mobile",                   sector: "Communication Services", industry: "Telecom",           type: "stock", marketCapBucket: "large" },
  { symbol: "EA",    name: "Electronic Arts",            sector: "Communication Services", industry: "Gaming",            type: "stock", marketCapBucket: "large" },
  { symbol: "TTWO",  name: "Take-Two Interactive",       sector: "Communication Services", industry: "Gaming",            type: "stock", marketCapBucket: "large" },
  { symbol: "IPG",   name: "Interpublic Group",          sector: "Communication Services", industry: "Advertising",       type: "stock", marketCapBucket: "large" },
  { symbol: "OMC",   name: "Omnicom Group",              sector: "Communication Services", industry: "Advertising",       type: "stock", marketCapBucket: "large" },
  { symbol: "PARA",  name: "Paramount Global",           sector: "Communication Services", industry: "Entertainment",     type: "stock", marketCapBucket: "large" },
  { symbol: "WBD",   name: "Warner Bros. Discovery",     sector: "Communication Services", industry: "Entertainment",     type: "stock", marketCapBucket: "large" },
  { symbol: "LYV",   name: "Live Nation",                sector: "Communication Services", industry: "Entertainment",     type: "stock", marketCapBucket: "large" },
  { symbol: "FOXA",  name: "Fox Corp (A)",               sector: "Communication Services", industry: "Broadcasting",      type: "stock", marketCapBucket: "large" },
  { symbol: "FOX",   name: "Fox Corp (B)",               sector: "Communication Services", industry: "Broadcasting",      type: "stock", marketCapBucket: "large" },
  { symbol: "NYT",   name: "New York Times",             sector: "Communication Services", industry: "Publishing",        type: "stock", marketCapBucket: "large" },
  { symbol: "MTCH",  name: "Match Group",                sector: "Communication Services", industry: "Internet",          type: "stock", marketCapBucket: "large" },
  { symbol: "ZG",    name: "Zillow Group",               sector: "Communication Services", industry: "Internet",          type: "stock", marketCapBucket: "large" },
  { symbol: "NWSA",  name: "News Corp (A)",              sector: "Communication Services", industry: "Publishing",        type: "stock", marketCapBucket: "large" },

  // ── Consumer Discretionary (~55) ─────────────────────────────────────────
  { symbol: "AMZN",  name: "Amazon",                     sector: "Consumer Discretionary", industry: "E-Commerce",          type: "stock", marketCapBucket: "mega"  },
  { symbol: "TSLA",  name: "Tesla",                      sector: "Consumer Discretionary", industry: "Electric Vehicles",   type: "stock", marketCapBucket: "mega"  },
  { symbol: "HD",    name: "Home Depot",                 sector: "Consumer Discretionary", industry: "Home Improvement",    type: "stock", marketCapBucket: "large" },
  { symbol: "MCD",   name: "McDonald's",                 sector: "Consumer Discretionary", industry: "Restaurants",         type: "stock", marketCapBucket: "large" },
  { symbol: "NKE",   name: "Nike",                       sector: "Consumer Discretionary", industry: "Footwear",            type: "stock", marketCapBucket: "large" },
  { symbol: "SBUX",  name: "Starbucks",                  sector: "Consumer Discretionary", industry: "Restaurants",         type: "stock", marketCapBucket: "large" },
  { symbol: "LOW",   name: "Lowe's",                     sector: "Consumer Discretionary", industry: "Home Improvement",    type: "stock", marketCapBucket: "large" },
  { symbol: "TJX",   name: "TJX Companies",              sector: "Consumer Discretionary", industry: "Apparel Retail",      type: "stock", marketCapBucket: "large" },
  { symbol: "BKNG",  name: "Booking Holdings",           sector: "Consumer Discretionary", industry: "Online Travel",       type: "stock", marketCapBucket: "large" },
  { symbol: "MAR",   name: "Marriott",                   sector: "Consumer Discretionary", industry: "Hotels",              type: "stock", marketCapBucket: "large" },
  { symbol: "HLT",   name: "Hilton",                     sector: "Consumer Discretionary", industry: "Hotels",              type: "stock", marketCapBucket: "large" },
  { symbol: "GM",    name: "General Motors",             sector: "Consumer Discretionary", industry: "Automobiles",         type: "stock", marketCapBucket: "large" },
  { symbol: "F",     name: "Ford Motor",                 sector: "Consumer Discretionary", industry: "Automobiles",         type: "stock", marketCapBucket: "large" },
  { symbol: "ORLY",  name: "O'Reilly Automotive",        sector: "Consumer Discretionary", industry: "Auto Parts",          type: "stock", marketCapBucket: "large" },
  { symbol: "AZO",   name: "AutoZone",                   sector: "Consumer Discretionary", industry: "Auto Parts",          type: "stock", marketCapBucket: "large" },
  { symbol: "GPC",   name: "Genuine Parts",              sector: "Consumer Discretionary", industry: "Auto Parts",          type: "stock", marketCapBucket: "large" },
  { symbol: "ROST",  name: "Ross Stores",                sector: "Consumer Discretionary", industry: "Apparel Retail",      type: "stock", marketCapBucket: "large" },
  { symbol: "BURL",  name: "Burlington Stores",          sector: "Consumer Discretionary", industry: "Apparel Retail",      type: "stock", marketCapBucket: "large" },
  { symbol: "TGT",   name: "Target",                     sector: "Consumer Discretionary", industry: "General Merchandise", type: "stock", marketCapBucket: "large" },
  { symbol: "DLTR",  name: "Dollar Tree",                sector: "Consumer Discretionary", industry: "Discount Stores",     type: "stock", marketCapBucket: "large" },
  { symbol: "DG",    name: "Dollar General",             sector: "Consumer Discretionary", industry: "Discount Stores",     type: "stock", marketCapBucket: "large" },
  { symbol: "BBY",   name: "Best Buy",                   sector: "Consumer Discretionary", industry: "Electronics Retail",  type: "stock", marketCapBucket: "large" },
  { symbol: "PHM",   name: "PulteGroup",                 sector: "Consumer Discretionary", industry: "Homebuilding",        type: "stock", marketCapBucket: "large" },
  { symbol: "DHI",   name: "D.R. Horton",                sector: "Consumer Discretionary", industry: "Homebuilding",        type: "stock", marketCapBucket: "large" },
  { symbol: "LEN",   name: "Lennar",                     sector: "Consumer Discretionary", industry: "Homebuilding",        type: "stock", marketCapBucket: "large" },
  { symbol: "NVR",   name: "NVR Inc",                    sector: "Consumer Discretionary", industry: "Homebuilding",        type: "stock", marketCapBucket: "large" },
  { symbol: "TOL",   name: "Toll Brothers",              sector: "Consumer Discretionary", industry: "Homebuilding",        type: "stock", marketCapBucket: "large" },
  { symbol: "CCL",   name: "Carnival",                   sector: "Consumer Discretionary", industry: "Cruise Lines",        type: "stock", marketCapBucket: "large" },
  { symbol: "RCL",   name: "Royal Caribbean",            sector: "Consumer Discretionary", industry: "Cruise Lines",        type: "stock", marketCapBucket: "large" },
  { symbol: "NCLH",  name: "Norwegian Cruise Line",      sector: "Consumer Discretionary", industry: "Cruise Lines",        type: "stock", marketCapBucket: "large" },
  { symbol: "MGM",   name: "MGM Resorts",                sector: "Consumer Discretionary", industry: "Casinos & Resorts",   type: "stock", marketCapBucket: "large" },
  { symbol: "LVS",   name: "Las Vegas Sands",            sector: "Consumer Discretionary", industry: "Casinos & Resorts",   type: "stock", marketCapBucket: "large" },
  { symbol: "WYNN",  name: "Wynn Resorts",               sector: "Consumer Discretionary", industry: "Casinos & Resorts",   type: "stock", marketCapBucket: "large" },
  { symbol: "CZR",   name: "Caesars Entertainment",      sector: "Consumer Discretionary", industry: "Casinos & Resorts",   type: "stock", marketCapBucket: "large" },
  { symbol: "EXPE",  name: "Expedia",                    sector: "Consumer Discretionary", industry: "Online Travel",       type: "stock", marketCapBucket: "large" },
  { symbol: "APTV",  name: "Aptiv",                      sector: "Consumer Discretionary", industry: "Auto Components",     type: "stock", marketCapBucket: "large" },
  { symbol: "BWA",   name: "BorgWarner",                 sector: "Consumer Discretionary", industry: "Auto Components",     type: "stock", marketCapBucket: "large" },
  { symbol: "RL",    name: "Ralph Lauren",               sector: "Consumer Discretionary", industry: "Apparel",             type: "stock", marketCapBucket: "large" },
  { symbol: "PVH",   name: "PVH Corp",                   sector: "Consumer Discretionary", industry: "Apparel",             type: "stock", marketCapBucket: "large" },
  { symbol: "TPR",   name: "Tapestry",                   sector: "Consumer Discretionary", industry: "Accessories",         type: "stock", marketCapBucket: "large" },
  { symbol: "HAS",   name: "Hasbro",                     sector: "Consumer Discretionary", industry: "Toys & Games",        type: "stock", marketCapBucket: "large" },
  { symbol: "MAT",   name: "Mattel",                     sector: "Consumer Discretionary", industry: "Toys & Games",        type: "stock", marketCapBucket: "large" },
  { symbol: "YUM",   name: "Yum! Brands",                sector: "Consumer Discretionary", industry: "Restaurants",         type: "stock", marketCapBucket: "large" },
  { symbol: "CMG",   name: "Chipotle",                   sector: "Consumer Discretionary", industry: "Restaurants",         type: "stock", marketCapBucket: "large" },
  { symbol: "DPZ",   name: "Domino's Pizza",             sector: "Consumer Discretionary", industry: "Restaurants",         type: "stock", marketCapBucket: "large" },
  { symbol: "LULU",  name: "Lululemon",                  sector: "Consumer Discretionary", industry: "Apparel",             type: "stock", marketCapBucket: "large" },
  { symbol: "ULTA",  name: "Ulta Beauty",                sector: "Consumer Discretionary", industry: "Beauty Retail",       type: "stock", marketCapBucket: "large" },
  { symbol: "EBAY",  name: "eBay",                       sector: "Consumer Discretionary", industry: "E-Commerce",          type: "stock", marketCapBucket: "large" },
  { symbol: "ETSY",  name: "Etsy",                       sector: "Consumer Discretionary", industry: "E-Commerce",          type: "stock", marketCapBucket: "large" },
  { symbol: "DECK",  name: "Deckers Outdoor",            sector: "Consumer Discretionary", industry: "Footwear",            type: "stock", marketCapBucket: "large" },
  { symbol: "POOL",  name: "Pool Corp",                  sector: "Consumer Discretionary", industry: "Wholesale Distribution", type: "stock", marketCapBucket: "large" },
  { symbol: "GNTX",  name: "Gentex Corp",                sector: "Consumer Discretionary", industry: "Auto Components",     type: "stock", marketCapBucket: "mid"  },
  { symbol: "ABNB",  name: "Airbnb",                     sector: "Consumer Discretionary", industry: "Online Travel",       type: "stock", marketCapBucket: "large" },
  { symbol: "H",     name: "Hyatt Hotels",               sector: "Consumer Discretionary", industry: "Hotels",              type: "stock", marketCapBucket: "large" },
  { symbol: "VFC",   name: "VF Corp",                    sector: "Consumer Discretionary", industry: "Apparel",             type: "stock", marketCapBucket: "large" },

  // ── Consumer Staples (~32) ────────────────────────────────────────────────
  { symbol: "WMT",   name: "Walmart",                    sector: "Consumer Staples", industry: "Food Retail",               type: "stock", marketCapBucket: "mega"  },
  { symbol: "PG",    name: "Procter & Gamble",           sector: "Consumer Staples", industry: "Household Products",        type: "stock", marketCapBucket: "mega"  },
  { symbol: "KO",    name: "Coca-Cola",                  sector: "Consumer Staples", industry: "Beverages",                 type: "stock", marketCapBucket: "mega"  },
  { symbol: "PEP",   name: "PepsiCo",                    sector: "Consumer Staples", industry: "Beverages",                 type: "stock", marketCapBucket: "mega"  },
  { symbol: "COST",  name: "Costco",                     sector: "Consumer Staples", industry: "Food Retail",               type: "stock", marketCapBucket: "mega"  },
  { symbol: "PM",    name: "Philip Morris",              sector: "Consumer Staples", industry: "Tobacco",                   type: "stock", marketCapBucket: "large" },
  { symbol: "MO",    name: "Altria Group",               sector: "Consumer Staples", industry: "Tobacco",                   type: "stock", marketCapBucket: "large" },
  { symbol: "MDLZ",  name: "Mondelez",                   sector: "Consumer Staples", industry: "Packaged Foods",            type: "stock", marketCapBucket: "large" },
  { symbol: "KHC",   name: "Kraft Heinz",                sector: "Consumer Staples", industry: "Packaged Foods",            type: "stock", marketCapBucket: "large" },
  { symbol: "GIS",   name: "General Mills",              sector: "Consumer Staples", industry: "Packaged Foods",            type: "stock", marketCapBucket: "large" },
  { symbol: "CAG",   name: "Conagra Brands",             sector: "Consumer Staples", industry: "Packaged Foods",            type: "stock", marketCapBucket: "large" },
  { symbol: "CPB",   name: "Campbell Soup",              sector: "Consumer Staples", industry: "Packaged Foods",            type: "stock", marketCapBucket: "large" },
  { symbol: "HRL",   name: "Hormel Foods",               sector: "Consumer Staples", industry: "Packaged Foods",            type: "stock", marketCapBucket: "large" },
  { symbol: "SJM",   name: "J.M. Smucker",               sector: "Consumer Staples", industry: "Packaged Foods",            type: "stock", marketCapBucket: "large" },
  { symbol: "CLX",   name: "Clorox",                     sector: "Consumer Staples", industry: "Household Products",        type: "stock", marketCapBucket: "large" },
  { symbol: "CL",    name: "Colgate-Palmolive",          sector: "Consumer Staples", industry: "Personal Care",             type: "stock", marketCapBucket: "large" },
  { symbol: "KMB",   name: "Kimberly-Clark",             sector: "Consumer Staples", industry: "Household Products",        type: "stock", marketCapBucket: "large" },
  { symbol: "CHD",   name: "Church & Dwight",            sector: "Consumer Staples", industry: "Household Products",        type: "stock", marketCapBucket: "large" },
  { symbol: "EL",    name: "Estee Lauder",               sector: "Consumer Staples", industry: "Personal Care",             type: "stock", marketCapBucket: "large" },
  { symbol: "KVUE",  name: "Kenvue",                     sector: "Consumer Staples", industry: "Personal Care",             type: "stock", marketCapBucket: "large" },
  { symbol: "TAP",   name: "Molson Coors",               sector: "Consumer Staples", industry: "Beverages",                 type: "stock", marketCapBucket: "large" },
  { symbol: "STZ",   name: "Constellation Brands",       sector: "Consumer Staples", industry: "Beverages",                 type: "stock", marketCapBucket: "large" },
  { symbol: "HSY",   name: "Hershey",                    sector: "Consumer Staples", industry: "Packaged Foods",            type: "stock", marketCapBucket: "large" },
  { symbol: "MKC",   name: "McCormick",                  sector: "Consumer Staples", industry: "Packaged Foods",            type: "stock", marketCapBucket: "large" },
  { symbol: "TSN",   name: "Tyson Foods",                sector: "Consumer Staples", industry: "Packaged Foods",            type: "stock", marketCapBucket: "large" },
  { symbol: "ADM",   name: "Archer-Daniels-Midland",     sector: "Consumer Staples", industry: "Agricultural Products",     type: "stock", marketCapBucket: "large" },
  { symbol: "KR",    name: "Kroger",                     sector: "Consumer Staples", industry: "Food Retail",               type: "stock", marketCapBucket: "large" },
  { symbol: "SYY",   name: "Sysco",                      sector: "Consumer Staples", industry: "Food Distribution",         type: "stock", marketCapBucket: "large" },
  { symbol: "USFD",  name: "US Foods",                   sector: "Consumer Staples", industry: "Food Distribution",         type: "stock", marketCapBucket: "large" },
  { symbol: "BF-B",  name: "Brown-Forman",               sector: "Consumer Staples", industry: "Beverages",                 type: "stock", marketCapBucket: "large" },
  { symbol: "MNST",  name: "Monster Beverage",           sector: "Consumer Staples", industry: "Beverages",                 type: "stock", marketCapBucket: "large" },
  { symbol: "COTY",  name: "Coty Inc",                   sector: "Consumer Staples", industry: "Personal Care",             type: "stock", marketCapBucket: "mid"  },

  // ── Energy (~22) ─────────────────────────────────────────────────────────
  { symbol: "XOM",   name: "ExxonMobil",                 sector: "Energy", industry: "Integrated Oil & Gas",    type: "stock", marketCapBucket: "mega"  },
  { symbol: "CVX",   name: "Chevron",                    sector: "Energy", industry: "Integrated Oil & Gas",    type: "stock", marketCapBucket: "mega"  },
  { symbol: "COP",   name: "ConocoPhillips",             sector: "Energy", industry: "E&P",                     type: "stock", marketCapBucket: "large" },
  { symbol: "EOG",   name: "EOG Resources",              sector: "Energy", industry: "E&P",                     type: "stock", marketCapBucket: "large" },
  { symbol: "SLB",   name: "SLB",                        sector: "Energy", industry: "Oil Field Services",      type: "stock", marketCapBucket: "large" },
  { symbol: "MPC",   name: "Marathon Petroleum",         sector: "Energy", industry: "Oil Refining",            type: "stock", marketCapBucket: "large" },
  { symbol: "PSX",   name: "Phillips 66",                sector: "Energy", industry: "Oil Refining",            type: "stock", marketCapBucket: "large" },
  { symbol: "VLO",   name: "Valero Energy",              sector: "Energy", industry: "Oil Refining",            type: "stock", marketCapBucket: "large" },
  { symbol: "OXY",   name: "Occidental Petroleum",       sector: "Energy", industry: "E&P",                     type: "stock", marketCapBucket: "large" },
  { symbol: "DVN",   name: "Devon Energy",               sector: "Energy", industry: "E&P",                     type: "stock", marketCapBucket: "large" },
  { symbol: "KMI",   name: "Kinder Morgan",              sector: "Energy", industry: "Pipelines",               type: "stock", marketCapBucket: "large" },
  { symbol: "WMB",   name: "Williams Companies",         sector: "Energy", industry: "Pipelines",               type: "stock", marketCapBucket: "large" },
  { symbol: "OKE",   name: "ONEOK",                      sector: "Energy", industry: "Pipelines",               type: "stock", marketCapBucket: "large" },
  { symbol: "BKR",   name: "Baker Hughes",               sector: "Energy", industry: "Oil Field Services",      type: "stock", marketCapBucket: "large" },
  { symbol: "HAL",   name: "Halliburton",                sector: "Energy", industry: "Oil Field Services",      type: "stock", marketCapBucket: "large" },
  { symbol: "FANG",  name: "Diamondback Energy",         sector: "Energy", industry: "E&P",                     type: "stock", marketCapBucket: "large" },
  { symbol: "MRO",   name: "Marathon Oil",               sector: "Energy", industry: "E&P",                     type: "stock", marketCapBucket: "large" },
  { symbol: "APA",   name: "APA Corp",                   sector: "Energy", industry: "E&P",                     type: "stock", marketCapBucket: "large" },
  { symbol: "CTRA",  name: "Coterra Energy",             sector: "Energy", industry: "E&P",                     type: "stock", marketCapBucket: "large" },
  { symbol: "HES",   name: "Hess Corp",                  sector: "Energy", industry: "E&P",                     type: "stock", marketCapBucket: "large" },
  { symbol: "EQT",   name: "EQT Corp",                   sector: "Energy", industry: "Natural Gas E&P",         type: "stock", marketCapBucket: "large" },
  { symbol: "TRGP",  name: "Targa Resources",            sector: "Energy", industry: "Pipelines",               type: "stock", marketCapBucket: "large" },
  { symbol: "LNG",   name: "Cheniere Energy",            sector: "Energy", industry: "LNG",                         type: "stock", marketCapBucket: "large" },

  // ── Financials (~70) ─────────────────────────────────────────────────────
  { symbol: "BRK-B", name: "Berkshire Hathaway B",       sector: "Financials", industry: "Diversified Financial",  type: "stock", marketCapBucket: "mega"  },
  { symbol: "JPM",   name: "JPMorgan Chase",             sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "mega"  },
  { symbol: "V",     name: "Visa",                       sector: "Financials", industry: "Payments",               type: "stock", marketCapBucket: "mega"  },
  { symbol: "MA",    name: "Mastercard",                 sector: "Financials", industry: "Payments",               type: "stock", marketCapBucket: "mega"  },
  { symbol: "BAC",   name: "Bank of America",            sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "WFC",   name: "Wells Fargo",                sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "GS",    name: "Goldman Sachs",              sector: "Financials", industry: "Investment Banking",     type: "stock", marketCapBucket: "large" },
  { symbol: "MS",    name: "Morgan Stanley",             sector: "Financials", industry: "Investment Banking",     type: "stock", marketCapBucket: "large" },
  { symbol: "BLK",   name: "BlackRock",                  sector: "Financials", industry: "Asset Management",       type: "stock", marketCapBucket: "large" },
  { symbol: "AXP",   name: "American Express",           sector: "Financials", industry: "Payments",               type: "stock", marketCapBucket: "large" },
  { symbol: "SPGI",  name: "S&P Global",                 sector: "Financials", industry: "Financial Data",         type: "stock", marketCapBucket: "large" },
  { symbol: "CB",    name: "Chubb",                      sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "PGR",   name: "Progressive",                sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "TRV",   name: "Travelers",                  sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "ALL",   name: "Allstate",                   sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "MET",   name: "MetLife",                    sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "PRU",   name: "Prudential Financial",       sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "AFL",   name: "Aflac",                      sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "AIG",   name: "AIG",                        sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "HIG",   name: "Hartford Financial",         sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "CINF",  name: "Cincinnati Financial",       sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "WTW",   name: "Willis Towers Watson",       sector: "Financials", industry: "Insurance Brokers",      type: "stock", marketCapBucket: "large" },
  { symbol: "AON",   name: "Aon",                        sector: "Financials", industry: "Insurance Brokers",      type: "stock", marketCapBucket: "large" },
  { symbol: "MMC",   name: "Marsh & McLennan",           sector: "Financials", industry: "Insurance Brokers",      type: "stock", marketCapBucket: "large" },
  { symbol: "AJG",   name: "Arthur J. Gallagher",        sector: "Financials", industry: "Insurance Brokers",      type: "stock", marketCapBucket: "large" },
  { symbol: "BRO",   name: "Brown & Brown",              sector: "Financials", industry: "Insurance Brokers",      type: "stock", marketCapBucket: "large" },
  { symbol: "EG",    name: "Everest Group",              sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "ACGL",  name: "Arch Capital",               sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "C",     name: "Citigroup",                  sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "USB",   name: "U.S. Bancorp",               sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "PNC",   name: "PNC Financial",              sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "TFC",   name: "Truist Financial",           sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "COF",   name: "Capital One",                sector: "Financials", industry: "Credit Cards",           type: "stock", marketCapBucket: "large" },
  { symbol: "DFS",   name: "Discover Financial",         sector: "Financials", industry: "Credit Cards",           type: "stock", marketCapBucket: "large" },
  { symbol: "SYF",   name: "Synchrony Financial",        sector: "Financials", industry: "Credit Cards",           type: "stock", marketCapBucket: "large" },
  { symbol: "FITB",  name: "Fifth Third Bancorp",        sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "HBAN",  name: "Huntington Bancshares",      sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "KEY",   name: "KeyCorp",                    sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "RF",    name: "Regions Financial",          sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "CFG",   name: "Citizens Financial",         sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "MTB",   name: "M&T Bank",                   sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "SCHW",  name: "Charles Schwab",             sector: "Financials", industry: "Brokerage",              type: "stock", marketCapBucket: "large" },
  { symbol: "TROW",  name: "T. Rowe Price",              sector: "Financials", industry: "Asset Management",       type: "stock", marketCapBucket: "large" },
  { symbol: "BEN",   name: "Franklin Resources",         sector: "Financials", industry: "Asset Management",       type: "stock", marketCapBucket: "large" },
  { symbol: "IVZ",   name: "Invesco",                    sector: "Financials", industry: "Asset Management",       type: "stock", marketCapBucket: "large" },
  { symbol: "FDS",   name: "FactSet Research",           sector: "Financials", industry: "Financial Data",         type: "stock", marketCapBucket: "large" },
  { symbol: "NDAQ",  name: "Nasdaq Inc",                 sector: "Financials", industry: "Exchanges",              type: "stock", marketCapBucket: "large" },
  { symbol: "ICE",   name: "Intercontinental Exchange",  sector: "Financials", industry: "Exchanges",              type: "stock", marketCapBucket: "large" },
  { symbol: "CME",   name: "CME Group",                  sector: "Financials", industry: "Exchanges",              type: "stock", marketCapBucket: "large" },
  { symbol: "CBOE",  name: "Cboe Global Markets",        sector: "Financials", industry: "Exchanges",              type: "stock", marketCapBucket: "large" },
  { symbol: "MCO",   name: "Moody's Corp",               sector: "Financials", industry: "Financial Data",         type: "stock", marketCapBucket: "large" },
  { symbol: "NTRS",  name: "Northern Trust",             sector: "Financials", industry: "Asset Management",       type: "stock", marketCapBucket: "large" },
  { symbol: "STT",   name: "State Street",               sector: "Financials", industry: "Asset Management",       type: "stock", marketCapBucket: "large" },
  { symbol: "BK",    name: "Bank of New York Mellon",    sector: "Financials", industry: "Asset Management",       type: "stock", marketCapBucket: "large" },
  { symbol: "FNF",   name: "Fidelity National Financial", sector: "Financials", industry: "Title Insurance",       type: "stock", marketCapBucket: "large" },
  { symbol: "PYPL",  name: "PayPal",                     sector: "Financials", industry: "Payments",               type: "stock", marketCapBucket: "large" },
  { symbol: "FI",    name: "Fiserv",                     sector: "Financials", industry: "Fintech",                type: "stock", marketCapBucket: "large" },
  { symbol: "FIS",   name: "Fidelity National Info Svcs", sector: "Financials", industry: "Fintech",               type: "stock", marketCapBucket: "large" },
  { symbol: "GPN",   name: "Global Payments",            sector: "Financials", industry: "Fintech",                type: "stock", marketCapBucket: "large" },
  { symbol: "RJF",   name: "Raymond James",              sector: "Financials", industry: "Brokerage",              type: "stock", marketCapBucket: "large" },
  { symbol: "AMP",   name: "Ameriprise Financial",       sector: "Financials", industry: "Asset Management",       type: "stock", marketCapBucket: "large" },
  { symbol: "PFG",   name: "Principal Financial",        sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "GL",    name: "Globe Life",                 sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "WRB",   name: "W.R. Berkley",               sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "ORI",   name: "Old Republic International", sector: "Financials", industry: "Insurance",              type: "stock", marketCapBucket: "large" },
  { symbol: "ALLY",  name: "Ally Financial",             sector: "Financials", industry: "Banking",                type: "stock", marketCapBucket: "large" },
  { symbol: "MKTX",  name: "MarketAxess",                sector: "Financials", industry: "Financial Services",     type: "stock", marketCapBucket: "large" },
  { symbol: "SEIC",  name: "SEI Investments",            sector: "Financials", industry: "Asset Management",       type: "stock", marketCapBucket: "large" },

  // ── Healthcare (~61) ─────────────────────────────────────────────────────
  { symbol: "LLY",   name: "Eli Lilly",                  sector: "Healthcare", industry: "Pharmaceuticals",        type: "stock", marketCapBucket: "mega"  },
  { symbol: "UNH",   name: "UnitedHealth Group",         sector: "Healthcare", industry: "Managed Care",           type: "stock", marketCapBucket: "mega"  },
  { symbol: "JNJ",   name: "Johnson & Johnson",          sector: "Healthcare", industry: "Pharmaceuticals",        type: "stock", marketCapBucket: "mega"  },
  { symbol: "ABBV",  name: "AbbVie",                     sector: "Healthcare", industry: "Pharmaceuticals",        type: "stock", marketCapBucket: "mega"  },
  { symbol: "MRK",   name: "Merck",                      sector: "Healthcare", industry: "Pharmaceuticals",        type: "stock", marketCapBucket: "mega"  },
  { symbol: "TMO",   name: "Thermo Fisher Scientific",   sector: "Healthcare", industry: "Life Sciences Tools",    type: "stock", marketCapBucket: "large" },
  { symbol: "ABT",   name: "Abbott Laboratories",        sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "DHR",   name: "Danaher",                    sector: "Healthcare", industry: "Life Sciences Tools",    type: "stock", marketCapBucket: "large" },
  { symbol: "PFE",   name: "Pfizer",                     sector: "Healthcare", industry: "Pharmaceuticals",        type: "stock", marketCapBucket: "large" },
  { symbol: "AMGN",  name: "Amgen",                      sector: "Healthcare", industry: "Biotechnology",          type: "stock", marketCapBucket: "large" },
  { symbol: "BSX",   name: "Boston Scientific",          sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "BMY",   name: "Bristol Myers Squibb",       sector: "Healthcare", industry: "Pharmaceuticals",        type: "stock", marketCapBucket: "large" },
  { symbol: "ISRG",  name: "Intuitive Surgical",         sector: "Healthcare", industry: "Medical Robots",         type: "stock", marketCapBucket: "large" },
  { symbol: "SYK",   name: "Stryker",                    sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "BDX",   name: "Becton Dickinson",           sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "ELV",   name: "Elevance Health",            sector: "Healthcare", industry: "Managed Care",           type: "stock", marketCapBucket: "large" },
  { symbol: "CI",    name: "Cigna",                      sector: "Healthcare", industry: "Managed Care",           type: "stock", marketCapBucket: "large" },
  { symbol: "HUM",   name: "Humana",                     sector: "Healthcare", industry: "Managed Care",           type: "stock", marketCapBucket: "large" },
  { symbol: "CVS",   name: "CVS Health",                 sector: "Healthcare", industry: "Pharmacy",               type: "stock", marketCapBucket: "large" },
  { symbol: "MCK",   name: "McKesson",                   sector: "Healthcare", industry: "Drug Distribution",      type: "stock", marketCapBucket: "large" },
  { symbol: "CAH",   name: "Cardinal Health",            sector: "Healthcare", industry: "Drug Distribution",      type: "stock", marketCapBucket: "large" },
  { symbol: "COR",   name: "Cencora",                    sector: "Healthcare", industry: "Drug Distribution",      type: "stock", marketCapBucket: "large" },
  { symbol: "BIIB",  name: "Biogen",                     sector: "Healthcare", industry: "Biotechnology",          type: "stock", marketCapBucket: "large" },
  { symbol: "GILD",  name: "Gilead Sciences",            sector: "Healthcare", industry: "Biotechnology",          type: "stock", marketCapBucket: "large" },
  { symbol: "REGN",  name: "Regeneron",                  sector: "Healthcare", industry: "Biotechnology",          type: "stock", marketCapBucket: "large" },
  { symbol: "VRTX",  name: "Vertex Pharmaceuticals",     sector: "Healthcare", industry: "Biotechnology",          type: "stock", marketCapBucket: "large" },
  { symbol: "IQV",   name: "IQVIA Holdings",             sector: "Healthcare", industry: "Life Sciences Tools",    type: "stock", marketCapBucket: "large" },
  { symbol: "A",     name: "Agilent Technologies",       sector: "Healthcare", industry: "Life Sciences Tools",    type: "stock", marketCapBucket: "large" },
  { symbol: "MTD",   name: "Mettler-Toledo",             sector: "Healthcare", industry: "Life Sciences Tools",    type: "stock", marketCapBucket: "large" },
  { symbol: "WAT",   name: "Waters Corp",                sector: "Healthcare", industry: "Life Sciences Tools",    type: "stock", marketCapBucket: "large" },
  { symbol: "IDXX",  name: "IDEXX Laboratories",         sector: "Healthcare", industry: "Veterinary Products",    type: "stock", marketCapBucket: "large" },
  { symbol: "HOLX",  name: "Hologic",                    sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "DXCM",  name: "DexCom",                     sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "MRNA",  name: "Moderna",                    sector: "Healthcare", industry: "Biotechnology",          type: "stock", marketCapBucket: "large" },
  { symbol: "RMD",   name: "ResMed",                     sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "ZTS",   name: "Zoetis",                     sector: "Healthcare", industry: "Animal Health",          type: "stock", marketCapBucket: "large" },
  { symbol: "CNC",   name: "Centene",                    sector: "Healthcare", industry: "Managed Care",           type: "stock", marketCapBucket: "large" },
  { symbol: "MOH",   name: "Molina Healthcare",          sector: "Healthcare", industry: "Managed Care",           type: "stock", marketCapBucket: "large" },
  { symbol: "HCA",   name: "HCA Healthcare",             sector: "Healthcare", industry: "Hospitals",              type: "stock", marketCapBucket: "large" },
  { symbol: "COO",   name: "Cooper Companies",           sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "ALGN",  name: "Align Technology",           sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "STE",   name: "STERIS",                     sector: "Healthcare", industry: "Medical Services",       type: "stock", marketCapBucket: "large" },
  { symbol: "GEHC",  name: "GE HealthCare",              sector: "Healthcare", industry: "Medical Imaging",        type: "stock", marketCapBucket: "large" },
  { symbol: "EW",    name: "Edwards Lifesciences",       sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "ZBH",   name: "Zimmer Biomet",              sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "MDT",   name: "Medtronic",                  sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "BAX",   name: "Baxter International",       sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "DVA",   name: "DaVita",                     sector: "Healthcare", industry: "Dialysis",               type: "stock", marketCapBucket: "large" },
  { symbol: "LH",    name: "Laboratory Corp",            sector: "Healthcare", industry: "Lab Services",           type: "stock", marketCapBucket: "large" },
  { symbol: "DGX",   name: "Quest Diagnostics",          sector: "Healthcare", industry: "Lab Services",           type: "stock", marketCapBucket: "large" },
  { symbol: "INCY",  name: "Incyte",                     sector: "Healthcare", industry: "Biotechnology",          type: "stock", marketCapBucket: "large" },
  { symbol: "PODD",  name: "Insulet",                    sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "TFX",   name: "Teleflex",                   sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "UHS",   name: "Universal Health Services",  sector: "Healthcare", industry: "Hospitals",              type: "stock", marketCapBucket: "large" },
  { symbol: "SOLV",  name: "Solventum",                  sector: "Healthcare", industry: "Medical Devices",        type: "stock", marketCapBucket: "large" },
  { symbol: "VTRS",  name: "Viatris",                    sector: "Healthcare", industry: "Generics",               type: "stock", marketCapBucket: "large" },
  { symbol: "HSIC",  name: "Henry Schein",               sector: "Healthcare", industry: "Medical Distribution",   type: "stock", marketCapBucket: "large" },
  { symbol: "TECH",  name: "Bio-Techne",                 sector: "Healthcare", industry: "Life Sciences Tools",    type: "stock", marketCapBucket: "large" },
  { symbol: "RVTY",  name: "Revvity",                    sector: "Healthcare", industry: "Life Sciences Tools",    type: "stock", marketCapBucket: "large" },
  { symbol: "ICLR",  name: "ICON plc",                   sector: "Healthcare", industry: "Life Sciences Tools",    type: "stock", marketCapBucket: "large" },
  { symbol: "OGN",   name: "Organon",                    sector: "Healthcare", industry: "Pharmaceuticals",        type: "stock", marketCapBucket: "large" },

  // ── Industrials (~79) ────────────────────────────────────────────────────
  { symbol: "GE",    name: "GE Aerospace",               sector: "Industrials", industry: "Aerospace & Defense",   type: "stock", marketCapBucket: "mega"  },
  { symbol: "RTX",   name: "RTX Corp",                   sector: "Industrials", industry: "Aerospace & Defense",   type: "stock", marketCapBucket: "large" },
  { symbol: "HON",   name: "Honeywell",                  sector: "Industrials", industry: "Conglomerates",         type: "stock", marketCapBucket: "large" },
  { symbol: "CAT",   name: "Caterpillar",                sector: "Industrials", industry: "Machinery",             type: "stock", marketCapBucket: "large" },
  { symbol: "UPS",   name: "UPS",                        sector: "Industrials", industry: "Air Freight",           type: "stock", marketCapBucket: "large" },
  { symbol: "DE",    name: "John Deere",                 sector: "Industrials", industry: "Farm Machinery",        type: "stock", marketCapBucket: "large" },
  { symbol: "BA",    name: "Boeing",                     sector: "Industrials", industry: "Aerospace & Defense",   type: "stock", marketCapBucket: "large" },
  { symbol: "LMT",   name: "Lockheed Martin",            sector: "Industrials", industry: "Aerospace & Defense",   type: "stock", marketCapBucket: "large" },
  { symbol: "NOC",   name: "Northrop Grumman",           sector: "Industrials", industry: "Aerospace & Defense",   type: "stock", marketCapBucket: "large" },
  { symbol: "GD",    name: "General Dynamics",           sector: "Industrials", industry: "Aerospace & Defense",   type: "stock", marketCapBucket: "large" },
  { symbol: "LHX",   name: "L3Harris Technologies",      sector: "Industrials", industry: "Aerospace & Defense",   type: "stock", marketCapBucket: "large" },
  { symbol: "HII",   name: "Huntington Ingalls",         sector: "Industrials", industry: "Aerospace & Defense",   type: "stock", marketCapBucket: "large" },
  { symbol: "TDG",   name: "TransDigm Group",            sector: "Industrials", industry: "Aerospace & Defense",   type: "stock", marketCapBucket: "large" },
  { symbol: "HWM",   name: "Howmet Aerospace",           sector: "Industrials", industry: "Aerospace & Defense",   type: "stock", marketCapBucket: "large" },
  { symbol: "AXON",  name: "Axon Enterprise",            sector: "Industrials", industry: "Defense Electronics",   type: "stock", marketCapBucket: "large" },
  { symbol: "LDOS",  name: "Leidos Holdings",            sector: "Industrials", industry: "Defense IT",            type: "stock", marketCapBucket: "large" },
  { symbol: "BAH",   name: "Booz Allen Hamilton",        sector: "Industrials", industry: "Defense IT",            type: "stock", marketCapBucket: "large" },
  { symbol: "SAIC",  name: "SAIC",                       sector: "Industrials", industry: "Defense IT",            type: "stock", marketCapBucket: "large" },
  { symbol: "FDX",   name: "FedEx",                      sector: "Industrials", industry: "Air Freight",           type: "stock", marketCapBucket: "large" },
  { symbol: "EXPD",  name: "Expeditors Int'l",           sector: "Industrials", industry: "Air Freight",           type: "stock", marketCapBucket: "large" },
  { symbol: "CHRW",  name: "C.H. Robinson",              sector: "Industrials", industry: "Logistics",             type: "stock", marketCapBucket: "large" },
  { symbol: "XPO",   name: "XPO Inc",                    sector: "Industrials", industry: "Trucking",              type: "stock", marketCapBucket: "large" },
  { symbol: "ODFL",  name: "Old Dominion Freight",       sector: "Industrials", industry: "Trucking",              type: "stock", marketCapBucket: "large" },
  { symbol: "JBHT",  name: "J.B. Hunt Transport",        sector: "Industrials", industry: "Trucking",              type: "stock", marketCapBucket: "large" },
  { symbol: "KNX",   name: "Knight-Swift",               sector: "Industrials", industry: "Trucking",              type: "stock", marketCapBucket: "large" },
  { symbol: "CSX",   name: "CSX Corp",                   sector: "Industrials", industry: "Railroads",             type: "stock", marketCapBucket: "large" },
  { symbol: "UNP",   name: "Union Pacific",              sector: "Industrials", industry: "Railroads",             type: "stock", marketCapBucket: "large" },
  { symbol: "NSC",   name: "Norfolk Southern",           sector: "Industrials", industry: "Railroads",             type: "stock", marketCapBucket: "large" },
  { symbol: "WAB",   name: "Wabtec",                     sector: "Industrials", industry: "Rail Equipment",        type: "stock", marketCapBucket: "large" },
  { symbol: "GWW",   name: "W.W. Grainger",              sector: "Industrials", industry: "Industrial Distribution", type: "stock", marketCapBucket: "large" },
  { symbol: "MMM",   name: "3M",                         sector: "Industrials", industry: "Conglomerates",         type: "stock", marketCapBucket: "large" },
  { symbol: "EMR",   name: "Emerson Electric",           sector: "Industrials", industry: "Industrial Automation", type: "stock", marketCapBucket: "large" },
  { symbol: "ETN",   name: "Eaton Corp",                 sector: "Industrials", industry: "Electrical Equipment",  type: "stock", marketCapBucket: "large" },
  { symbol: "PH",    name: "Parker Hannifin",            sector: "Industrials", industry: "Industrial Machinery",  type: "stock", marketCapBucket: "large" },
  { symbol: "ITW",   name: "Illinois Tool Works",        sector: "Industrials", industry: "Industrial Machinery",  type: "stock", marketCapBucket: "large" },
  { symbol: "CARR",  name: "Carrier Global",             sector: "Industrials", industry: "HVAC",                  type: "stock", marketCapBucket: "large" },
  { symbol: "OTIS",  name: "Otis Worldwide",             sector: "Industrials", industry: "Elevators",             type: "stock", marketCapBucket: "large" },
  { symbol: "TT",    name: "Trane Technologies",         sector: "Industrials", industry: "HVAC",                  type: "stock", marketCapBucket: "large" },
  { symbol: "IR",    name: "Ingersoll Rand",             sector: "Industrials", industry: "Industrial Machinery",  type: "stock", marketCapBucket: "large" },
  { symbol: "XYL",   name: "Xylem",                      sector: "Industrials", industry: "Water Equipment",       type: "stock", marketCapBucket: "large" },
  { symbol: "VLTO",  name: "Veralto",                    sector: "Industrials", industry: "Environmental Services", type: "stock", marketCapBucket: "large" },
  { symbol: "AME",   name: "AMETEK",                     sector: "Industrials", industry: "Electronic Instruments", type: "stock", marketCapBucket: "large" },
  { symbol: "FTV",   name: "Fortive",                    sector: "Industrials", industry: "Industrial Automation",  type: "stock", marketCapBucket: "large" },
  { symbol: "FAST",  name: "Fastenal",                   sector: "Industrials", industry: "Industrial Distribution", type: "stock", marketCapBucket: "large" },
  { symbol: "SNA",   name: "Snap-on",                    sector: "Industrials", industry: "Industrial Tools",       type: "stock", marketCapBucket: "large" },
  { symbol: "ROK",   name: "Rockwell Automation",        sector: "Industrials", industry: "Industrial Automation",  type: "stock", marketCapBucket: "large" },
  { symbol: "DOV",   name: "Dover Corp",                 sector: "Industrials", industry: "Industrial Machinery",   type: "stock", marketCapBucket: "large" },
  { symbol: "GNRC",  name: "Generac",                    sector: "Industrials", industry: "Power Generation",       type: "stock", marketCapBucket: "large" },
  { symbol: "CPRT",  name: "Copart",                     sector: "Industrials", industry: "Auto Auction",           type: "stock", marketCapBucket: "large" },
  { symbol: "RSG",   name: "Republic Services",          sector: "Industrials", industry: "Waste Management",       type: "stock", marketCapBucket: "large" },
  { symbol: "WM",    name: "Waste Management",           sector: "Industrials", industry: "Waste Management",       type: "stock", marketCapBucket: "large" },
  { symbol: "CTAS",  name: "Cintas",                     sector: "Industrials", industry: "Business Services",      type: "stock", marketCapBucket: "large" },
  { symbol: "PAYX",  name: "Paychex",                    sector: "Industrials", industry: "Payroll Services",       type: "stock", marketCapBucket: "large" },
  { symbol: "ADP",   name: "ADP",                        sector: "Industrials", industry: "HR Services",            type: "stock", marketCapBucket: "large" },
  { symbol: "VRSK",  name: "Verisk Analytics",           sector: "Industrials", industry: "Data Services",          type: "stock", marketCapBucket: "large" },
  { symbol: "EFX",   name: "Equifax",                    sector: "Industrials", industry: "Data Services",          type: "stock", marketCapBucket: "large" },
  { symbol: "TRU",   name: "TransUnion",                 sector: "Industrials", industry: "Data Services",          type: "stock", marketCapBucket: "large" },
  { symbol: "CBRE",  name: "CBRE Group",                 sector: "Industrials", industry: "Real Estate Services",   type: "stock", marketCapBucket: "large" },
  { symbol: "JCI",   name: "Johnson Controls",           sector: "Industrials", industry: "Building Products",      type: "stock", marketCapBucket: "large" },
  { symbol: "PWR",   name: "Quanta Services",            sector: "Industrials", industry: "Engineering Services",   type: "stock", marketCapBucket: "large" },
  { symbol: "URI",   name: "United Rentals",             sector: "Industrials", industry: "Equipment Rental",        type: "stock", marketCapBucket: "large" },
  { symbol: "HUBB",  name: "Hubbell",                    sector: "Industrials", industry: "Electrical Products",    type: "stock", marketCapBucket: "large" },
  { symbol: "ALLE",  name: "Allegion",                   sector: "Industrials", industry: "Security Products",      type: "stock", marketCapBucket: "large" },
  { symbol: "SWK",   name: "Stanley Black & Decker",     sector: "Industrials", industry: "Hand Tools",             type: "stock", marketCapBucket: "large" },
  { symbol: "BALL",  name: "Ball Corp",                  sector: "Industrials", industry: "Packaging",              type: "stock", marketCapBucket: "large" },
  { symbol: "PKG",   name: "Packaging Corp",             sector: "Industrials", industry: "Packaging",              type: "stock", marketCapBucket: "large" },
  { symbol: "IP",    name: "International Paper",        sector: "Industrials", industry: "Paper & Packaging",      type: "stock", marketCapBucket: "large" },
  { symbol: "SON",   name: "Sonoco Products",            sector: "Industrials", industry: "Packaging",              type: "stock", marketCapBucket: "large" },
  { symbol: "PCAR",  name: "PACCAR",                     sector: "Industrials", industry: "Trucks",                 type: "stock", marketCapBucket: "large" },
  { symbol: "CMI",   name: "Cummins",                    sector: "Industrials", industry: "Engines",                type: "stock", marketCapBucket: "large" },
  { symbol: "ROL",   name: "Rollins",                    sector: "Industrials", industry: "Pest Control",           type: "stock", marketCapBucket: "large" },
  { symbol: "NDSN",  name: "Nordson",                    sector: "Industrials", industry: "Industrial Equipment",   type: "stock", marketCapBucket: "large" },
  { symbol: "MAS",   name: "Masco",                      sector: "Industrials", industry: "Building Products",      type: "stock", marketCapBucket: "large" },
  { symbol: "PNR",   name: "Pentair",                    sector: "Industrials", industry: "Industrial Machinery",   type: "stock", marketCapBucket: "large" },
  { symbol: "J",     name: "Jacobs Engineering",         sector: "Industrials", industry: "Engineering Services",   type: "stock", marketCapBucket: "large" },
  { symbol: "GXO",   name: "GXO Logistics",              sector: "Industrials", industry: "Logistics",              type: "stock", marketCapBucket: "large" },
  { symbol: "RRX",   name: "Regal Rexnord",              sector: "Industrials", industry: "Industrial Machinery",   type: "stock", marketCapBucket: "large" },

  // ── Materials (~27) ──────────────────────────────────────────────────────
  { symbol: "LIN",   name: "Linde",                      sector: "Materials", industry: "Industrial Gases",        type: "stock", marketCapBucket: "mega"  },
  { symbol: "APD",   name: "Air Products",               sector: "Materials", industry: "Industrial Gases",        type: "stock", marketCapBucket: "large" },
  { symbol: "SHW",   name: "Sherwin-Williams",           sector: "Materials", industry: "Specialty Chemicals",     type: "stock", marketCapBucket: "large" },
  { symbol: "FCX",   name: "Freeport-McMoRan",           sector: "Materials", industry: "Copper Mining",           type: "stock", marketCapBucket: "large" },
  { symbol: "NEM",   name: "Newmont",                    sector: "Materials", industry: "Gold Mining",             type: "stock", marketCapBucket: "large" },
  { symbol: "NUE",   name: "Nucor",                      sector: "Materials", industry: "Steel",                   type: "stock", marketCapBucket: "large" },
  { symbol: "STLD",  name: "Steel Dynamics",             sector: "Materials", industry: "Steel",                   type: "stock", marketCapBucket: "large" },
  { symbol: "ALB",   name: "Albemarle",                  sector: "Materials", industry: "Specialty Chemicals",     type: "stock", marketCapBucket: "large" },
  { symbol: "ECL",   name: "Ecolab",                     sector: "Materials", industry: "Specialty Chemicals",     type: "stock", marketCapBucket: "large" },
  { symbol: "PPG",   name: "PPG Industries",             sector: "Materials", industry: "Specialty Chemicals",     type: "stock", marketCapBucket: "large" },
  { symbol: "DOW",   name: "Dow Inc",                    sector: "Materials", industry: "Chemicals",               type: "stock", marketCapBucket: "large" },
  { symbol: "DD",    name: "DuPont",                     sector: "Materials", industry: "Specialty Chemicals",     type: "stock", marketCapBucket: "large" },
  { symbol: "EMN",   name: "Eastman Chemical",           sector: "Materials", industry: "Chemicals",               type: "stock", marketCapBucket: "large" },
  { symbol: "CE",    name: "Celanese",                   sector: "Materials", industry: "Chemicals",               type: "stock", marketCapBucket: "large" },
  { symbol: "IFF",   name: "Intl Flavors & Fragrances",  sector: "Materials", industry: "Specialty Chemicals",     type: "stock", marketCapBucket: "large" },
  { symbol: "RPM",   name: "RPM International",          sector: "Materials", industry: "Specialty Chemicals",     type: "stock", marketCapBucket: "large" },
  { symbol: "AVY",   name: "Avery Dennison",             sector: "Materials", industry: "Specialty Chemicals",     type: "stock", marketCapBucket: "large" },
  { symbol: "MLM",   name: "Martin Marietta",            sector: "Materials", industry: "Construction Aggregates", type: "stock", marketCapBucket: "large" },
  { symbol: "VMC",   name: "Vulcan Materials",           sector: "Materials", industry: "Construction Aggregates", type: "stock", marketCapBucket: "large" },
  { symbol: "MOS",   name: "Mosaic Co",                  sector: "Materials", industry: "Fertilizers",             type: "stock", marketCapBucket: "large" },
  { symbol: "CF",    name: "CF Industries",              sector: "Materials", industry: "Fertilizers",             type: "stock", marketCapBucket: "large" },
  { symbol: "FMC",   name: "FMC Corp",                   sector: "Materials", industry: "Agricultural Chemicals",  type: "stock", marketCapBucket: "large" },
  { symbol: "AA",    name: "Alcoa",                      sector: "Materials", industry: "Aluminum",                type: "stock", marketCapBucket: "large" },
  { symbol: "ATI",   name: "ATI Inc",                    sector: "Materials", industry: "Specialty Metals",        type: "stock", marketCapBucket: "mid"  },
  { symbol: "SEE",   name: "Sealed Air",                 sector: "Materials", industry: "Packaging",               type: "stock", marketCapBucket: "large" },
  { symbol: "AMCR",  name: "Amcor",                      sector: "Materials", industry: "Packaging",               type: "stock", marketCapBucket: "large" },
  { symbol: "X",     name: "U.S. Steel",                 sector: "Materials", industry: "Steel",                   type: "stock", marketCapBucket: "large" },

  // ── Real Estate (~32) ────────────────────────────────────────────────────
  { symbol: "AMT",   name: "American Tower",             sector: "Real Estate", industry: "Cell Tower REITs",      type: "stock", marketCapBucket: "large" },
  { symbol: "PLD",   name: "Prologis",                   sector: "Real Estate", industry: "Industrial REITs",      type: "stock", marketCapBucket: "large" },
  { symbol: "EQIX",  name: "Equinix",                    sector: "Real Estate", industry: "Data Center REITs",     type: "stock", marketCapBucket: "large" },
  { symbol: "CCI",   name: "Crown Castle",               sector: "Real Estate", industry: "Cell Tower REITs",      type: "stock", marketCapBucket: "large" },
  { symbol: "SBAC",  name: "SBA Communications",         sector: "Real Estate", industry: "Cell Tower REITs",      type: "stock", marketCapBucket: "large" },
  { symbol: "DLR",   name: "Digital Realty",             sector: "Real Estate", industry: "Data Center REITs",     type: "stock", marketCapBucket: "large" },
  { symbol: "PSA",   name: "Public Storage",             sector: "Real Estate", industry: "Self-Storage REITs",    type: "stock", marketCapBucket: "large" },
  { symbol: "EXR",   name: "Extra Space Storage",        sector: "Real Estate", industry: "Self-Storage REITs",    type: "stock", marketCapBucket: "large" },
  { symbol: "WELL",  name: "Welltower",                  sector: "Real Estate", industry: "Healthcare REITs",      type: "stock", marketCapBucket: "large" },
  { symbol: "VICI",  name: "VICI Properties",            sector: "Real Estate", industry: "Casino REITs",          type: "stock", marketCapBucket: "large" },
  { symbol: "O",     name: "Realty Income",              sector: "Real Estate", industry: "Net Lease REITs",       type: "stock", marketCapBucket: "large" },
  { symbol: "ARE",   name: "Alexandria Real Estate",     sector: "Real Estate", industry: "Office REITs",          type: "stock", marketCapBucket: "large" },
  { symbol: "BXP",   name: "Boston Properties",          sector: "Real Estate", industry: "Office REITs",          type: "stock", marketCapBucket: "large" },
  { symbol: "VTR",   name: "Ventas",                     sector: "Real Estate", industry: "Healthcare REITs",      type: "stock", marketCapBucket: "large" },
  { symbol: "HST",   name: "Host Hotels",                sector: "Real Estate", industry: "Hotel REITs",           type: "stock", marketCapBucket: "large" },
  { symbol: "AVB",   name: "AvalonBay Communities",      sector: "Real Estate", industry: "Apartment REITs",       type: "stock", marketCapBucket: "large" },
  { symbol: "EQR",   name: "Equity Residential",         sector: "Real Estate", industry: "Apartment REITs",       type: "stock", marketCapBucket: "large" },
  { symbol: "ESS",   name: "Essex Property Trust",       sector: "Real Estate", industry: "Apartment REITs",       type: "stock", marketCapBucket: "large" },
  { symbol: "MAA",   name: "Mid-America Apartment",      sector: "Real Estate", industry: "Apartment REITs",       type: "stock", marketCapBucket: "large" },
  { symbol: "CPT",   name: "Camden Property Trust",      sector: "Real Estate", industry: "Apartment REITs",       type: "stock", marketCapBucket: "large" },
  { symbol: "UDR",   name: "UDR Inc",                    sector: "Real Estate", industry: "Apartment REITs",       type: "stock", marketCapBucket: "large" },
  { symbol: "FRT",   name: "Federal Realty",             sector: "Real Estate", industry: "Retail REITs",          type: "stock", marketCapBucket: "large" },
  { symbol: "REG",   name: "Regency Centers",            sector: "Real Estate", industry: "Retail REITs",          type: "stock", marketCapBucket: "large" },
  { symbol: "KIM",   name: "Kimco Realty",               sector: "Real Estate", industry: "Retail REITs",          type: "stock", marketCapBucket: "large" },
  { symbol: "SPG",   name: "Simon Property Group",       sector: "Real Estate", industry: "Retail REITs",          type: "stock", marketCapBucket: "large" },
  { symbol: "IRM",   name: "Iron Mountain",              sector: "Real Estate", industry: "Specialty REITs",       type: "stock", marketCapBucket: "large" },
  { symbol: "CSGP",  name: "CoStar Group",               sector: "Real Estate", industry: "Real Estate Data",      type: "stock", marketCapBucket: "large" },
  { symbol: "NNN",   name: "NNN REIT",                   sector: "Real Estate", industry: "Net Lease REITs",       type: "stock", marketCapBucket: "large" },
  { symbol: "INVH",  name: "Invitation Homes",           sector: "Real Estate", industry: "Residential REITs",     type: "stock", marketCapBucket: "large" },
  { symbol: "SUI",   name: "Sun Communities",            sector: "Real Estate", industry: "Specialty REITs",       type: "stock", marketCapBucket: "large" },
  { symbol: "WY",    name: "Weyerhaeuser",               sector: "Real Estate", industry: "Timber REITs",          type: "stock", marketCapBucket: "large" },
  { symbol: "ELS",   name: "Equity LifeStyle Properties", sector: "Real Estate", industry: "Specialty REITs",     type: "stock", marketCapBucket: "large" },

  // ── Utilities (~32) ──────────────────────────────────────────────────────
  { symbol: "NEE",   name: "NextEra Energy",             sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "mega"  },
  { symbol: "DUK",   name: "Duke Energy",                sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "SO",    name: "Southern Company",           sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "D",     name: "Dominion Energy",            sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "AEP",   name: "American Electric Power",    sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "EXC",   name: "Exelon",                     sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "XEL",   name: "Xcel Energy",                sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "SRE",   name: "Sempra",                     sector: "Utilities", industry: "Gas & Electric",          type: "stock", marketCapBucket: "large" },
  { symbol: "PCG",   name: "PG&E Corp",                  sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "ED",    name: "Consolidated Edison",        sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "WEC",   name: "WEC Energy",                 sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "ETR",   name: "Entergy",                    sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "FE",    name: "FirstEnergy",                sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "PPL",   name: "PPL Corp",                   sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "AWK",   name: "American Water Works",       sector: "Utilities", industry: "Water Utilities",         type: "stock", marketCapBucket: "large" },
  { symbol: "CNP",   name: "CenterPoint Energy",         sector: "Utilities", industry: "Gas & Electric",          type: "stock", marketCapBucket: "large" },
  { symbol: "NI",    name: "NiSource",                   sector: "Utilities", industry: "Gas Utilities",           type: "stock", marketCapBucket: "large" },
  { symbol: "AES",   name: "AES Corp",                   sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "DTE",   name: "DTE Energy",                 sector: "Utilities", industry: "Gas & Electric",          type: "stock", marketCapBucket: "large" },
  { symbol: "LNT",   name: "Alliant Energy",             sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "ES",    name: "Eversource Energy",          sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "EVRG",  name: "Evergy",                     sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "ATO",   name: "Atmos Energy",               sector: "Utilities", industry: "Gas Utilities",           type: "stock", marketCapBucket: "large" },
  { symbol: "PNW",   name: "Pinnacle West Capital",      sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "OGE",   name: "OGE Energy",                 sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "large" },
  { symbol: "WTRG",  name: "Essential Utilities",        sector: "Utilities", industry: "Water Utilities",         type: "stock", marketCapBucket: "large" },
  { symbol: "BKH",   name: "Black Hills Corp",           sector: "Utilities", industry: "Gas & Electric",          type: "stock", marketCapBucket: "mid"  },
  { symbol: "SWX",   name: "Southwest Gas",              sector: "Utilities", industry: "Gas Utilities",           type: "stock", marketCapBucket: "mid"  },
  { symbol: "NWE",   name: "NorthWestern Energy",        sector: "Utilities", industry: "Gas & Electric",          type: "stock", marketCapBucket: "mid"  },
  { symbol: "IDACORP", name: "IDACORP",                  sector: "Utilities", industry: "Electric Utilities",      type: "stock", marketCapBucket: "mid"  },
  { symbol: "CMS",   name: "CMS Energy",                 sector: "Utilities", industry: "Gas & Electric",          type: "stock", marketCapBucket: "large" },
  { symbol: "AEE",   name: "Ameren",                     sector: "Utilities", industry: "Gas & Electric",          type: "stock", marketCapBucket: "large" },
];

// ─── Sector ETFs ──────────────────────────────────────────────────────────────
export const SECTOR_ETFS: UniverseInstrument[] = [
  { symbol: "XLK", name: "Tech Sector ETF", sector: "Technology", type: "etf", marketCapBucket: "mega" },
  { symbol: "XLC", name: "Comm Services ETF", sector: "Communication Services", type: "etf", marketCapBucket: "large" },
  { symbol: "XLY", name: "Cons Discretionary ETF", sector: "Consumer Discretionary", type: "etf", marketCapBucket: "large" },
  { symbol: "XLP", name: "Cons Staples ETF", sector: "Consumer Staples", type: "etf", marketCapBucket: "large" },
  { symbol: "XLV", name: "Healthcare ETF", sector: "Healthcare", type: "etf", marketCapBucket: "large" },
  { symbol: "XLF", name: "Financials ETF", sector: "Financials", type: "etf", marketCapBucket: "large" },
  { symbol: "XLE", name: "Energy ETF", sector: "Energy", type: "etf", marketCapBucket: "large" },
  { symbol: "XLI", name: "Industrials ETF", sector: "Industrials", type: "etf", marketCapBucket: "large" },
  { symbol: "XLRE", name: "Real Estate ETF", sector: "Real Estate", type: "etf", marketCapBucket: "mid" },
  { symbol: "XLU", name: "Utilities ETF", sector: "Utilities", type: "etf", marketCapBucket: "mid" },
  { symbol: "XLB", name: "Materials ETF", sector: "Materials", type: "etf", marketCapBucket: "mid" },
];

// ─── Watchlist definitions (add custom watchlists here) ──────────────────────
export interface Watchlist {
  id: string;
  label: string;
  instruments: UniverseInstrument[];
}

export const WATCHLISTS: Watchlist[] = [
  { id: "mag7",        label: "Magnificent 7", instruments: MAG7         },
  { id: "sp500",       label: "S&P 500",       instruments: SP500        },
  // { id: "sector-etfs", label: "Sector ETFs",   instruments: SECTOR_ETFS },
];

export const DEFAULT_WATCHLIST_ID = "mag7";

export function getWatchlist(id: string): Watchlist {
  return WATCHLISTS.find((w) => w.id === id) ?? WATCHLISTS[0];
}

// Market cap bucket → numeric weight (for treemap sizing)
const BUCKET_WEIGHTS: Record<string, number> = {
  mega: 4,
  large: 2,
  mid: 1,
  small: 0.5,
};

export function getMarketCapWeight(instrument: UniverseInstrument): number {
  return BUCKET_WEIGHTS[instrument.marketCapBucket ?? "mid"] ?? 1;
}
